#ifndef FEJIX_REGISTRY_H_
#define FEJIX_REGISTRY_H_


enum fj_registry {
    FJ_PUBLIC_ID_SPACE_BEGIN = 0,

    FJ_CLIENT_LISTENER,
    FJ_WINDOW_MANAGER_LISTENER,
    FJ_WINDOW_LISTENER,
    FJ_WINDOW_CONFIG_LISTENER,

    FJ_PUBLIC_ID_SPACE_END = 999,

    FJ_PRIVATE_ID_SPACE_BEGIN = 1000,
    
    FJ_PRIVATE_ID_SPACE_END = 9999,

    FJ_USER_ID_SPACE_BEGIN = 10000,
};


#endif
