/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/app.h>

fj_err_t fj_app_check_supported(void)
{

    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_app_create(struct fj_app ** out_app, struct fj_app_create_info const * info)
{
    (void) out_app; (void) info;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_app_destroy(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNSUPPORTED;
}

void fj_app_on_idle(struct fj_app * app, fj_app_on_idle_fn_t callback)
{
    (void) app; (void) callback;
    /* do nothing by default */;
}

void fj_app_on_finish(struct fj_app * app, fj_app_on_finish_fn_t callback)
{
    (void) app; (void) callback;
    /* do nothing by default */;
}

void fj_app_on_notification(struct fj_app * app, fj_app_on_notification_fn_t callback)
{
    (void) app; (void) callback;
    /* do nothing by default */;
}

fj_err_t fj_app_launch(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNSUPPORTED;
}

void fj_app_wakeup_after_timeout(struct fj_app * app, fj_seconds_t timeout)
{
    (void) app; (void) timeout;
    /* do nothing by default */;
}

fj_err_t fj_app_wakeup_remotely(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNSUPPORTED;
}

void fj_app_set_finished(struct fj_app * app)
{
    (void) app;
    /* do nothing by default */;
}

