/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/image.h>

void fj_image_create_event_get_desired_size(struct fj_image_create_event * crete_event, struct fj_size * out_size)
{
    (void) crete_event; (void) out_size;
    /* do nothing by default */;
}

