/* Automatically generated by tools/autogen.py, do not edit! */


#include <fejix/interface/image_consumer.h>
void fj_image_consumer_get_desired_size(struct fj_image_consumer * image_consumer, struct fj_size * out_size)
{
    (void) image_consumer; (void) out_size;
    /* do nothing by default */;
}

