/* Automatically generated by autogen.py, do not edit! */


#include <fejix/interface/implementation.h>
void fj_implementation_get_id(fj_implementation_id_t * out_id)
{
    (void) out_id;
    /* do nothing by default */;
}

void fj_implementation_get_name(char const ** out_name)
{
    (void) out_name;
    /* do nothing by default */;
}

void fj_implementation_get_version(fj_version_t * out_version)
{
    (void) out_version;
    /* do nothing by default */;
}

