/* Automatically generated by autogen.py, do not edit! */


#include <fejix/interface/app_activity_flags.h>
#include <loader.h>
fj_loader_function_t _fj_app_activity_flags_get_supported_flags_ptr;
fj_app_activity_flags_t fj_app_activity_flags_get_supported_flags(struct fj_app * app)
{
    if (_fj_app_activity_flags_get_supported_flags_ptr != NULL) {
        return ((fj_app_activity_flags_t(*)(struct fj_app * app))_fj_app_activity_flags_get_supported_flags_ptr)(app);
    }
    return 0;
}

fj_loader_function_t _fj_app_activity_flags_set_flags_ptr;
fj_err_t fj_app_activity_flags_set_flags(struct fj_app * app, fj_app_activity_flags_t flags)
{
    if (_fj_app_activity_flags_set_flags_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app, fj_app_activity_flags_t flags))_fj_app_activity_flags_set_flags_ptr)(app, flags);
    }
    return FJ_ERR_UNSUPPORTED;
}

