/* Automatically generated by autogen.py, do not edit! */


#include <fejix/interface/image_consumer.h>
#include <loader.h>
fj_loader_function_t _fj_image_consumer_get_desired_size_ptr;
void fj_image_consumer_get_desired_size(struct fj_image_consumer * image_consumer, struct fj_size * out_size)
{
    if (_fj_image_consumer_get_desired_size_ptr != NULL) {
        ((void(*)(struct fj_image_consumer * image_consumer, struct fj_size * out_size))_fj_image_consumer_get_desired_size_ptr)(image_consumer, out_size);
    }
    /* do nothing by default */;
}

