#ifndef FEJIX_INTERNAL_INTERFACE_WRAPPER_H_
#define FEJIX_INTERNAL_INTERFACE_WRAPPER_H_


#define FJ_WRAP_VOID_FUNCTION(FUNCTION, ARGS, CONVERTED_ARGS) \
    static void FUNCTION##_wrapped ARGS { FUNCTION CONVERTED_ARGS; }
#define FJ_WRAP_FUNCTION(FUNCTION, TYPE, ARGS, CONVERTED_ARGS) \
    static TYPE FUNCTION##_wrapped ARGS { return FUNCTION CONVERTED_ARGS; }
#define FJ_WRAP_IFACE_BEGIN(IFACE_TYPE, IFACE_IMPL) struct IFACE_TYPE IFACE_IMPL = {
#define FJ_WRAP_IFACE_END };
#define FJ_WRAP_IFACE_METHOD(METHOD, FUNCTION) .METHOD = FUCNTION##_wrapped,


#endif
