/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader.h>

char const *fj_loader_function_names[] = {
    "fj_app_get_interface_version",
    "fj_app_create",
    "fj_app_destroy",
    "fj_app_on_continue",
    "f_app_on_suspend",
    "fj_app_on_finish",
    "fj_app_launch",
    "fj_app_request_continue",
    "fj_app_request_finish",
    "fj_app_activity_get_interface_version",
    "fj_app_activity_set_flags",
    "fj_app_clock_get_interface_version",
    "fj_app_clock_create",
    "fj_app_clock_destroy",
    "fj_app_clock_start_ticking",
    "fj_app_clock_stop_ticking",
    "fj_app_clock_on_tick",
    "fj_app_clock_get_remaining_time",
    "fj_app_manual_sleep_get_interface_version",
    "fj_app_manual_sleep",
    "fj_implementation_get_name",
    "fj_implementation_get_version",
    "fj_ram_get_interface_version",
    "fj_ram_create_manager",
    "fj_ram_destroy_manager",
    "fj_ram_get_supported_formats",
    "fj_ram_create_images",
    "fj_ram_destroy_images",
    "fj_ram_resize_images",
    "fj_ram_wait_image_available",
    "fj_ram_get_available_image_info",
    "fj_ram_present_image",
    "fj_view_get_interface_version",
    "fj_view_create_manager",
    "fj_view_destroy_manager",
    "fj_view_create",
    "fj_view_destroy",
    "fj_view_on_bind_images",
    "fj_view_on_dismiss",
    "fj_view_on_update_geometry",
    "fj_view_update_batch",
};

extern fj_loader_function_t _fj_app_get_interface_version_ptr;
extern fj_loader_function_t _fj_app_create_ptr;
extern fj_loader_function_t _fj_app_destroy_ptr;
extern fj_loader_function_t _fj_app_on_continue_ptr;
extern fj_loader_function_t _f_app_on_suspend_ptr;
extern fj_loader_function_t _fj_app_on_finish_ptr;
extern fj_loader_function_t _fj_app_launch_ptr;
extern fj_loader_function_t _fj_app_request_continue_ptr;
extern fj_loader_function_t _fj_app_request_finish_ptr;
extern fj_loader_function_t _fj_app_activity_get_interface_version_ptr;
extern fj_loader_function_t _fj_app_activity_set_flags_ptr;
extern fj_loader_function_t _fj_app_clock_get_interface_version_ptr;
extern fj_loader_function_t _fj_app_clock_create_ptr;
extern fj_loader_function_t _fj_app_clock_destroy_ptr;
extern fj_loader_function_t _fj_app_clock_start_ticking_ptr;
extern fj_loader_function_t _fj_app_clock_stop_ticking_ptr;
extern fj_loader_function_t _fj_app_clock_on_tick_ptr;
extern fj_loader_function_t _fj_app_clock_get_remaining_time_ptr;
extern fj_loader_function_t _fj_app_manual_sleep_get_interface_version_ptr;
extern fj_loader_function_t _fj_app_manual_sleep_ptr;
extern fj_loader_function_t _fj_implementation_get_name_ptr;
extern fj_loader_function_t _fj_implementation_get_version_ptr;
extern fj_loader_function_t _fj_ram_get_interface_version_ptr;
extern fj_loader_function_t _fj_ram_create_manager_ptr;
extern fj_loader_function_t _fj_ram_destroy_manager_ptr;
extern fj_loader_function_t _fj_ram_get_supported_formats_ptr;
extern fj_loader_function_t _fj_ram_create_images_ptr;
extern fj_loader_function_t _fj_ram_destroy_images_ptr;
extern fj_loader_function_t _fj_ram_resize_images_ptr;
extern fj_loader_function_t _fj_ram_wait_image_available_ptr;
extern fj_loader_function_t _fj_ram_get_available_image_info_ptr;
extern fj_loader_function_t _fj_ram_present_image_ptr;
extern fj_loader_function_t _fj_view_get_interface_version_ptr;
extern fj_loader_function_t _fj_view_create_manager_ptr;
extern fj_loader_function_t _fj_view_destroy_manager_ptr;
extern fj_loader_function_t _fj_view_create_ptr;
extern fj_loader_function_t _fj_view_destroy_ptr;
extern fj_loader_function_t _fj_view_on_bind_images_ptr;
extern fj_loader_function_t _fj_view_on_dismiss_ptr;
extern fj_loader_function_t _fj_view_on_update_geometry_ptr;
extern fj_loader_function_t _fj_view_update_batch_ptr;

fj_loader_function_t *fj_loader_function_pointers[] = {
    (fj_loader_function_t*)&_fj_app_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_app_create_ptr,
    (fj_loader_function_t*)&_fj_app_destroy_ptr,
    (fj_loader_function_t*)&_fj_app_on_continue_ptr,
    (fj_loader_function_t*)&_f_app_on_suspend_ptr,
    (fj_loader_function_t*)&_fj_app_on_finish_ptr,
    (fj_loader_function_t*)&_fj_app_launch_ptr,
    (fj_loader_function_t*)&_fj_app_request_continue_ptr,
    (fj_loader_function_t*)&_fj_app_request_finish_ptr,
    (fj_loader_function_t*)&_fj_app_activity_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_app_activity_set_flags_ptr,
    (fj_loader_function_t*)&_fj_app_clock_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_app_clock_create_ptr,
    (fj_loader_function_t*)&_fj_app_clock_destroy_ptr,
    (fj_loader_function_t*)&_fj_app_clock_start_ticking_ptr,
    (fj_loader_function_t*)&_fj_app_clock_stop_ticking_ptr,
    (fj_loader_function_t*)&_fj_app_clock_on_tick_ptr,
    (fj_loader_function_t*)&_fj_app_clock_get_remaining_time_ptr,
    (fj_loader_function_t*)&_fj_app_manual_sleep_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_app_manual_sleep_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_name_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_version_ptr,
    (fj_loader_function_t*)&_fj_ram_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_ram_create_manager_ptr,
    (fj_loader_function_t*)&_fj_ram_destroy_manager_ptr,
    (fj_loader_function_t*)&_fj_ram_get_supported_formats_ptr,
    (fj_loader_function_t*)&_fj_ram_create_images_ptr,
    (fj_loader_function_t*)&_fj_ram_destroy_images_ptr,
    (fj_loader_function_t*)&_fj_ram_resize_images_ptr,
    (fj_loader_function_t*)&_fj_ram_wait_image_available_ptr,
    (fj_loader_function_t*)&_fj_ram_get_available_image_info_ptr,
    (fj_loader_function_t*)&_fj_ram_present_image_ptr,
    (fj_loader_function_t*)&_fj_view_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_view_create_manager_ptr,
    (fj_loader_function_t*)&_fj_view_destroy_manager_ptr,
    (fj_loader_function_t*)&_fj_view_create_ptr,
    (fj_loader_function_t*)&_fj_view_destroy_ptr,
    (fj_loader_function_t*)&_fj_view_on_bind_images_ptr,
    (fj_loader_function_t*)&_fj_view_on_dismiss_ptr,
    (fj_loader_function_t*)&_fj_view_on_update_geometry_ptr,
    (fj_loader_function_t*)&_fj_view_update_batch_ptr,
};

uint32_t fj_loader_function_count = 41;
