/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader.h>

char const *fj_loader_function_names[] = {
    "fj_has_app",
    "fj_app_create",
    "fj_app_destroy",
    "fj_app_on_continue",
    "f_app_on_suspend",
    "fj_app_on_finish",
    "fj_app_launch",
    "fj_app_request_continue",
    "fj_app_request_finish",
    "fj_app_activity_get_interface_version",
    "fj_app_activity_set_flags",
    "fj_has_app_clock",
    "fj_app_clock_create",
    "fj_app_clock_destroy",
    "fj_app_clock_start_ticking",
    "fj_app_clock_stop_ticking",
    "fj_app_clock_on_tick",
    "fj_app_clock_get_remaining_time",
    "fj_has_app_manual_sleep",
    "fj_app_manual_sleep",
    "fj_implementation_get_name",
    "fj_implementation_get_version",
    "fj_has_opengl",
    "fj_opengl_has_platform",
    "fj_opengl_create_default_platform",
    "fj_opengl_destroy_default_platform",
    "fj_opengl_create_manager",
    "fj_opengl_destroy_manager",
    "fj_opengl_get_manager_platform",
    "fj_opengl_get_manager_extensions",
    "fj_opengl_get_manager_feature_flags",
    "fj_opengl_create_offscreen_image_binding",
    "fj_opengl_destroy_offscreen_image_binding",
    "fj_opengl_can_bind",
    "fj_opengl_create_image_format",
    "fj_opengl_destroy_image_format",
    "fj_opengl_get_image_format_attribute",
    "fj_opengl_create_images",
    "fj_opengl_destroy_images",
    "fj_opengl_get_images_image_format",
    "fj_opengl_get_images_platform_object",
    "fj_opengl_swap_images",
    "fj_opengl_create_renderer",
    "fj_opengl_destroy_renderer",
    "fj_opengl_get_renderer_attribute",
    "fj_opengl_get_renderer_image_format",
    "fj_opengl_get_renderer_platform_object",
    "fj_opengl_get_renderer_function_getter",
    "fj_opengl_set_current_in_thread",
    "fj_opengl_unset_current_in_thread",
    "fj_opengl_set_dummy_current_in_thread",
    "fj_ram_get_interface_version",
    "fj_ram_create_manager",
    "fj_ram_destroy_manager",
    "fj_ram_get_supported_formats",
    "fj_ram_create_images",
    "fj_ram_destroy_images",
    "fj_ram_resize_images",
    "fj_ram_wait_image_available",
    "fj_ram_get_available_image_info",
    "fj_ram_present_image",
    "fj_has_view",
    "fj_view_create_manager",
    "fj_view_destroy_manager",
    "fj_view_create",
    "fj_view_destroy",
    "fj_view_on_bind_images",
    "fj_view_on_dismiss",
    "fj_view_on_update_geometry",
    "fj_view_update_batch",
    "fj_has_vulkan",
    "fj_vulkan_create_surface",
};

extern fj_loader_function_t _fj_has_app_ptr;
extern fj_loader_function_t _fj_app_create_ptr;
extern fj_loader_function_t _fj_app_destroy_ptr;
extern fj_loader_function_t _fj_app_on_continue_ptr;
extern fj_loader_function_t _f_app_on_suspend_ptr;
extern fj_loader_function_t _fj_app_on_finish_ptr;
extern fj_loader_function_t _fj_app_launch_ptr;
extern fj_loader_function_t _fj_app_request_continue_ptr;
extern fj_loader_function_t _fj_app_request_finish_ptr;
extern fj_loader_function_t _fj_app_activity_get_interface_version_ptr;
extern fj_loader_function_t _fj_app_activity_set_flags_ptr;
extern fj_loader_function_t _fj_has_app_clock_ptr;
extern fj_loader_function_t _fj_app_clock_create_ptr;
extern fj_loader_function_t _fj_app_clock_destroy_ptr;
extern fj_loader_function_t _fj_app_clock_start_ticking_ptr;
extern fj_loader_function_t _fj_app_clock_stop_ticking_ptr;
extern fj_loader_function_t _fj_app_clock_on_tick_ptr;
extern fj_loader_function_t _fj_app_clock_get_remaining_time_ptr;
extern fj_loader_function_t _fj_has_app_manual_sleep_ptr;
extern fj_loader_function_t _fj_app_manual_sleep_ptr;
extern fj_loader_function_t _fj_implementation_get_name_ptr;
extern fj_loader_function_t _fj_implementation_get_version_ptr;
extern fj_loader_function_t _fj_has_opengl_ptr;
extern fj_loader_function_t _fj_opengl_has_platform_ptr;
extern fj_loader_function_t _fj_opengl_create_default_platform_ptr;
extern fj_loader_function_t _fj_opengl_destroy_default_platform_ptr;
extern fj_loader_function_t _fj_opengl_create_manager_ptr;
extern fj_loader_function_t _fj_opengl_destroy_manager_ptr;
extern fj_loader_function_t _fj_opengl_get_manager_platform_ptr;
extern fj_loader_function_t _fj_opengl_get_manager_extensions_ptr;
extern fj_loader_function_t _fj_opengl_get_manager_feature_flags_ptr;
extern fj_loader_function_t _fj_opengl_create_offscreen_image_binding_ptr;
extern fj_loader_function_t _fj_opengl_destroy_offscreen_image_binding_ptr;
extern fj_loader_function_t _fj_opengl_can_bind_ptr;
extern fj_loader_function_t _fj_opengl_create_image_format_ptr;
extern fj_loader_function_t _fj_opengl_destroy_image_format_ptr;
extern fj_loader_function_t _fj_opengl_get_image_format_attribute_ptr;
extern fj_loader_function_t _fj_opengl_create_images_ptr;
extern fj_loader_function_t _fj_opengl_destroy_images_ptr;
extern fj_loader_function_t _fj_opengl_get_images_image_format_ptr;
extern fj_loader_function_t _fj_opengl_get_images_platform_object_ptr;
extern fj_loader_function_t _fj_opengl_swap_images_ptr;
extern fj_loader_function_t _fj_opengl_create_renderer_ptr;
extern fj_loader_function_t _fj_opengl_destroy_renderer_ptr;
extern fj_loader_function_t _fj_opengl_get_renderer_attribute_ptr;
extern fj_loader_function_t _fj_opengl_get_renderer_image_format_ptr;
extern fj_loader_function_t _fj_opengl_get_renderer_platform_object_ptr;
extern fj_loader_function_t _fj_opengl_get_renderer_function_getter_ptr;
extern fj_loader_function_t _fj_opengl_set_current_in_thread_ptr;
extern fj_loader_function_t _fj_opengl_unset_current_in_thread_ptr;
extern fj_loader_function_t _fj_opengl_set_dummy_current_in_thread_ptr;
extern fj_loader_function_t _fj_ram_get_interface_version_ptr;
extern fj_loader_function_t _fj_ram_create_manager_ptr;
extern fj_loader_function_t _fj_ram_destroy_manager_ptr;
extern fj_loader_function_t _fj_ram_get_supported_formats_ptr;
extern fj_loader_function_t _fj_ram_create_images_ptr;
extern fj_loader_function_t _fj_ram_destroy_images_ptr;
extern fj_loader_function_t _fj_ram_resize_images_ptr;
extern fj_loader_function_t _fj_ram_wait_image_available_ptr;
extern fj_loader_function_t _fj_ram_get_available_image_info_ptr;
extern fj_loader_function_t _fj_ram_present_image_ptr;
extern fj_loader_function_t _fj_has_view_ptr;
extern fj_loader_function_t _fj_view_create_manager_ptr;
extern fj_loader_function_t _fj_view_destroy_manager_ptr;
extern fj_loader_function_t _fj_view_create_ptr;
extern fj_loader_function_t _fj_view_destroy_ptr;
extern fj_loader_function_t _fj_view_on_bind_images_ptr;
extern fj_loader_function_t _fj_view_on_dismiss_ptr;
extern fj_loader_function_t _fj_view_on_update_geometry_ptr;
extern fj_loader_function_t _fj_view_update_batch_ptr;
extern fj_loader_function_t _fj_has_vulkan_ptr;
extern fj_loader_function_t _fj_vulkan_create_surface_ptr;

fj_loader_function_t *fj_loader_function_pointers[] = {
    (fj_loader_function_t*)&_fj_has_app_ptr,
    (fj_loader_function_t*)&_fj_app_create_ptr,
    (fj_loader_function_t*)&_fj_app_destroy_ptr,
    (fj_loader_function_t*)&_fj_app_on_continue_ptr,
    (fj_loader_function_t*)&_f_app_on_suspend_ptr,
    (fj_loader_function_t*)&_fj_app_on_finish_ptr,
    (fj_loader_function_t*)&_fj_app_launch_ptr,
    (fj_loader_function_t*)&_fj_app_request_continue_ptr,
    (fj_loader_function_t*)&_fj_app_request_finish_ptr,
    (fj_loader_function_t*)&_fj_app_activity_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_app_activity_set_flags_ptr,
    (fj_loader_function_t*)&_fj_has_app_clock_ptr,
    (fj_loader_function_t*)&_fj_app_clock_create_ptr,
    (fj_loader_function_t*)&_fj_app_clock_destroy_ptr,
    (fj_loader_function_t*)&_fj_app_clock_start_ticking_ptr,
    (fj_loader_function_t*)&_fj_app_clock_stop_ticking_ptr,
    (fj_loader_function_t*)&_fj_app_clock_on_tick_ptr,
    (fj_loader_function_t*)&_fj_app_clock_get_remaining_time_ptr,
    (fj_loader_function_t*)&_fj_has_app_manual_sleep_ptr,
    (fj_loader_function_t*)&_fj_app_manual_sleep_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_name_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_version_ptr,
    (fj_loader_function_t*)&_fj_has_opengl_ptr,
    (fj_loader_function_t*)&_fj_opengl_has_platform_ptr,
    (fj_loader_function_t*)&_fj_opengl_create_default_platform_ptr,
    (fj_loader_function_t*)&_fj_opengl_destroy_default_platform_ptr,
    (fj_loader_function_t*)&_fj_opengl_create_manager_ptr,
    (fj_loader_function_t*)&_fj_opengl_destroy_manager_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_manager_platform_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_manager_extensions_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_manager_feature_flags_ptr,
    (fj_loader_function_t*)&_fj_opengl_create_offscreen_image_binding_ptr,
    (fj_loader_function_t*)&_fj_opengl_destroy_offscreen_image_binding_ptr,
    (fj_loader_function_t*)&_fj_opengl_can_bind_ptr,
    (fj_loader_function_t*)&_fj_opengl_create_image_format_ptr,
    (fj_loader_function_t*)&_fj_opengl_destroy_image_format_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_image_format_attribute_ptr,
    (fj_loader_function_t*)&_fj_opengl_create_images_ptr,
    (fj_loader_function_t*)&_fj_opengl_destroy_images_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_images_image_format_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_images_platform_object_ptr,
    (fj_loader_function_t*)&_fj_opengl_swap_images_ptr,
    (fj_loader_function_t*)&_fj_opengl_create_renderer_ptr,
    (fj_loader_function_t*)&_fj_opengl_destroy_renderer_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_renderer_attribute_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_renderer_image_format_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_renderer_platform_object_ptr,
    (fj_loader_function_t*)&_fj_opengl_get_renderer_function_getter_ptr,
    (fj_loader_function_t*)&_fj_opengl_set_current_in_thread_ptr,
    (fj_loader_function_t*)&_fj_opengl_unset_current_in_thread_ptr,
    (fj_loader_function_t*)&_fj_opengl_set_dummy_current_in_thread_ptr,
    (fj_loader_function_t*)&_fj_ram_get_interface_version_ptr,
    (fj_loader_function_t*)&_fj_ram_create_manager_ptr,
    (fj_loader_function_t*)&_fj_ram_destroy_manager_ptr,
    (fj_loader_function_t*)&_fj_ram_get_supported_formats_ptr,
    (fj_loader_function_t*)&_fj_ram_create_images_ptr,
    (fj_loader_function_t*)&_fj_ram_destroy_images_ptr,
    (fj_loader_function_t*)&_fj_ram_resize_images_ptr,
    (fj_loader_function_t*)&_fj_ram_wait_image_available_ptr,
    (fj_loader_function_t*)&_fj_ram_get_available_image_info_ptr,
    (fj_loader_function_t*)&_fj_ram_present_image_ptr,
    (fj_loader_function_t*)&_fj_has_view_ptr,
    (fj_loader_function_t*)&_fj_view_create_manager_ptr,
    (fj_loader_function_t*)&_fj_view_destroy_manager_ptr,
    (fj_loader_function_t*)&_fj_view_create_ptr,
    (fj_loader_function_t*)&_fj_view_destroy_ptr,
    (fj_loader_function_t*)&_fj_view_on_bind_images_ptr,
    (fj_loader_function_t*)&_fj_view_on_dismiss_ptr,
    (fj_loader_function_t*)&_fj_view_on_update_geometry_ptr,
    (fj_loader_function_t*)&_fj_view_update_batch_ptr,
    (fj_loader_function_t*)&_fj_has_vulkan_ptr,
    (fj_loader_function_t*)&_fj_vulkan_create_surface_ptr,
};

uint32_t fj_loader_function_count = 72;
