/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/app.h>

fj_loader_function_t _fj_app_get_interface_version_ptr;
fj_version_t fj_app_get_interface_version(void)
{
    if (_fj_app_get_interface_version_ptr != NULL) {
        return ((fj_version_t(*)(void))_fj_app_get_interface_version_ptr)();
    }
    return 0;
}

fj_loader_function_t _fj_app_create_ptr;
fj_err_t fj_app_create(struct fj_app ** out_app, void * app_userdata)
{
    if (_fj_app_create_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app ** out_app, void * app_userdata))_fj_app_create_ptr)(out_app, app_userdata);
    }
    return FJ_ERR_UNSUPPORTED;
}

fj_loader_function_t _fj_app_destroy_ptr;
fj_err_t fj_app_destroy(struct fj_app * app)
{
    if (_fj_app_destroy_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app))_fj_app_destroy_ptr)(app);
    }
    return FJ_ERR_UNSUPPORTED;
}

fj_loader_function_t _fj_app_on_continue_ptr;
void fj_app_on_continue(struct fj_app * app, fj_app_on_continue_fn_t callback)
{
    if (_fj_app_on_continue_ptr != NULL) {
        ((void(*)(struct fj_app * app, fj_app_on_continue_fn_t callback))_fj_app_on_continue_ptr)(app, callback);
    }
    /* do nothing by default */;
}

fj_loader_function_t _f_app_on_suspend_ptr;
void f_app_on_suspend(struct fj_app * app, fj_app_on_suspend_fn_t callback)
{
    if (_f_app_on_suspend_ptr != NULL) {
        ((void(*)(struct fj_app * app, fj_app_on_suspend_fn_t callback))_f_app_on_suspend_ptr)(app, callback);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_app_on_finish_ptr;
void fj_app_on_finish(struct fj_app * app, fj_app_on_finish_fn_t callback)
{
    if (_fj_app_on_finish_ptr != NULL) {
        ((void(*)(struct fj_app * app, fj_app_on_finish_fn_t callback))_fj_app_on_finish_ptr)(app, callback);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_app_launch_ptr;
fj_err_t fj_app_launch(struct fj_app * app)
{
    if (_fj_app_launch_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app))_fj_app_launch_ptr)(app);
    }
    return FJ_ERR_UNSUPPORTED;
}

fj_loader_function_t _fj_app_request_continue_ptr;
fj_err_t fj_app_request_continue(struct fj_app * app)
{
    if (_fj_app_request_continue_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app))_fj_app_request_continue_ptr)(app);
    }
    return FJ_ERR_UNSUPPORTED;
}

fj_loader_function_t _fj_app_request_finish_ptr;
fj_err_t fj_app_request_finish(struct fj_app * app)
{
    if (_fj_app_request_finish_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app))_fj_app_request_finish_ptr)(app);
    }
    return FJ_ERR_UNSUPPORTED;
}

