/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/app_manual_sleep.h>

fj_loader_function_t _fj_app_manual_sleep_get_interface_version_ptr;
bool fj_app_manual_sleep_get_interface_version(void)
{
    if (_fj_app_manual_sleep_get_interface_version_ptr != NULL) {
        return ((bool(*)(void))_fj_app_manual_sleep_get_interface_version_ptr)();
    }
    return 0;
}

fj_loader_function_t _fj_app_manual_sleep_ptr;
fj_err_t fj_app_manual_sleep(struct fj_app * app)
{
    if (_fj_app_manual_sleep_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app))_fj_app_manual_sleep_ptr)(app);
    }
    return FJ_ERR_UNSUPPORTED;
}

