/* Automatically generated by tools/autogen/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/implementation.h>

void *_fj_implementation_set_global_ptr;
void fj_implementation_set_global(struct fj_implementation const * implementation)
{
    if (_fj_implementation_set_global_ptr != NULL)
        ((void(*)(struct fj_implementation const * implementation))_fj_implementation_set_global_ptr)(implementation);
    /* do nothing by default */;
}

void *_fj_implementation_get_global_ptr;
struct fj_implementation const * fj_implementation_get_global(void)
{
    if (_fj_implementation_get_global_ptr != NULL)
        return ((struct fj_implementation const *(*)(void))_fj_implementation_get_global_ptr)();
    return 0;
}

void *_fj_implementation_get_name_ptr;
char const * fj_implementation_get_name(fj_implementation_id_t id)
{
    if (_fj_implementation_get_name_ptr != NULL)
        return ((char const *(*)(fj_implementation_id_t id))_fj_implementation_get_name_ptr)(id);
    return 0;
}

void *_fj_implementation_get_builtin_ptr;
struct fj_implementation const * fj_implementation_get_builtin(fj_implementation_id_t id)
{
    if (_fj_implementation_get_builtin_ptr != NULL)
        return ((struct fj_implementation const *(*)(fj_implementation_id_t id))_fj_implementation_get_builtin_ptr)(id);
    return 0;
}

void *_fj_implementation_get_default_id_ptr;
fj_err_t fj_implementation_get_default_id(fj_implementation_id_t * out_id)
{
    if (_fj_implementation_get_default_id_ptr != NULL)
        return ((fj_err_t(*)(fj_implementation_id_t * out_id))_fj_implementation_get_default_id_ptr)(out_id);
    return FJ_ERR_UNSUPPORTED;
}
