/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/implementation.h>

fj_loader_function_t _fj_implementation_get_name_ptr;
char const * fj_implementation_get_name(void)
{
    if (_fj_implementation_get_name_ptr != NULL) {
        return ((char const *(*)(void))_fj_implementation_get_name_ptr)();
    }
    return NULL;
}

fj_loader_function_t _fj_implementation_get_version_ptr;
fj_version_t fj_implementation_get_version(void)
{
    if (_fj_implementation_get_version_ptr != NULL) {
        return ((fj_version_t(*)(void))_fj_implementation_get_version_ptr)();
    }
    return 0;
}

