/* Automatically generated by tools/autogen/autogen.py, do not edit! */

#include <src/loader/loadable.h>

#include <fejix/interface/app.h>

static fj_err_t (*fj_app_check_supported_ptr)(void);
fj_err_t fj_app_check_supported(void)
{
    if (fj_app_check_supported_ptr != NULL)
        return fj_app_check_supported_ptr();
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_app_create_ptr)(struct fj_app ** out_app, struct fj_app_create_info const * info);
fj_err_t fj_app_create(struct fj_app ** out_app, struct fj_app_create_info const * info)
{
    if (fj_app_create_ptr != NULL)
        return fj_app_create_ptr(out_app, info);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_app_destroy_ptr)(struct fj_app * app);
fj_err_t fj_app_destroy(struct fj_app * app)
{
    if (fj_app_destroy_ptr != NULL)
        return fj_app_destroy_ptr(app);
    return FJ_ERR_UNSUPPORTED;
}

static void (*fj_app_on_idle_ptr)(struct fj_app * app, fj_app_on_idle_fn_t callback);
void fj_app_on_idle(struct fj_app * app, fj_app_on_idle_fn_t callback)
{
    if (fj_app_on_idle_ptr != NULL)
        fj_app_on_idle_ptr(app, callback);
    /* do nothing by default */;
}

static void (*fj_app_on_finish_ptr)(struct fj_app * app, fj_app_on_finish_fn_t callback);
void fj_app_on_finish(struct fj_app * app, fj_app_on_finish_fn_t callback)
{
    if (fj_app_on_finish_ptr != NULL)
        fj_app_on_finish_ptr(app, callback);
    /* do nothing by default */;
}

static void (*fj_app_on_notification_ptr)(struct fj_app * app, fj_app_on_notification_fn_t callback);
void fj_app_on_notification(struct fj_app * app, fj_app_on_notification_fn_t callback)
{
    if (fj_app_on_notification_ptr != NULL)
        fj_app_on_notification_ptr(app, callback);
    /* do nothing by default */;
}

static fj_err_t (*fj_app_launch_ptr)(struct fj_app * app);
fj_err_t fj_app_launch(struct fj_app * app)
{
    if (fj_app_launch_ptr != NULL)
        return fj_app_launch_ptr(app);
    return FJ_ERR_UNSUPPORTED;
}

static void (*fj_app_wakeup_after_timeout_ptr)(struct fj_app * app, fj_seconds_t timeout);
void fj_app_wakeup_after_timeout(struct fj_app * app, fj_seconds_t timeout)
{
    if (fj_app_wakeup_after_timeout_ptr != NULL)
        fj_app_wakeup_after_timeout_ptr(app, timeout);
    /* do nothing by default */;
}

static fj_err_t (*fj_app_wakeup_remotely_ptr)(struct fj_app * app);
fj_err_t fj_app_wakeup_remotely(struct fj_app * app)
{
    if (fj_app_wakeup_remotely_ptr != NULL)
        return fj_app_wakeup_remotely_ptr(app);
    return FJ_ERR_UNSUPPORTED;
}

static void (*fj_app_set_finished_ptr)(struct fj_app * app);
void fj_app_set_finished(struct fj_app * app)
{
    if (fj_app_set_finished_ptr != NULL)
        fj_app_set_finished_ptr(app);
    /* do nothing by default */;
}

#include <fejix/interface/app_activity_flags.h>

static fj_app_activity_flags_t (*fj_app_activity_flags_get_supported_flags_ptr)(struct fj_app * app);
fj_app_activity_flags_t fj_app_activity_flags_get_supported_flags(struct fj_app * app)
{
    if (fj_app_activity_flags_get_supported_flags_ptr != NULL)
        return fj_app_activity_flags_get_supported_flags_ptr(app);
    return 0;
}

static fj_err_t (*fj_app_activity_flags_set_flags_ptr)(struct fj_app * app, fj_app_activity_flags_t flags);
fj_err_t fj_app_activity_flags_set_flags(struct fj_app * app, fj_app_activity_flags_t flags)
{
    if (fj_app_activity_flags_set_flags_ptr != NULL)
        return fj_app_activity_flags_set_flags_ptr(app, flags);
    return FJ_ERR_UNSUPPORTED;
}

#include <fejix/interface/app_manual_sleep.h>

static bool (*fj_app_manual_sleep_get_supported_ptr)(void);
bool fj_app_manual_sleep_get_supported(void)
{
    if (fj_app_manual_sleep_get_supported_ptr != NULL)
        return fj_app_manual_sleep_get_supported_ptr();
    return 0;
}

static fj_err_t (*fj_app_manual_sleep_ptr)(struct fj_app * app);
fj_err_t fj_app_manual_sleep(struct fj_app * app)
{
    if (fj_app_manual_sleep_ptr != NULL)
        return fj_app_manual_sleep_ptr(app);
    return FJ_ERR_UNSUPPORTED;
}

#include <fejix/interface/image_consumer.h>

static void (*fj_image_consumer_get_desired_size_ptr)(struct fj_image_consumer * image_consumer, struct fj_size * out_size);
void fj_image_consumer_get_desired_size(struct fj_image_consumer * image_consumer, struct fj_size * out_size)
{
    if (fj_image_consumer_get_desired_size_ptr != NULL)
        fj_image_consumer_get_desired_size_ptr(image_consumer, out_size);
    /* do nothing by default */;
}

#include <fejix/interface/implementation.h>

static void (*fj_implementation_set_global_ptr)(struct fj_implementation const * implementation);
void fj_implementation_set_global(struct fj_implementation const * implementation)
{
    if (fj_implementation_set_global_ptr != NULL)
        fj_implementation_set_global_ptr(implementation);
    /* do nothing by default */;
}

static struct fj_implementation const * (*fj_implementation_get_global_ptr)(void);
struct fj_implementation const * fj_implementation_get_global(void)
{
    if (fj_implementation_get_global_ptr != NULL)
        return fj_implementation_get_global_ptr();
    return 0;
}

static char const * (*fj_implementation_get_name_ptr)(fj_implementation_id_t id);
char const * fj_implementation_get_name(fj_implementation_id_t id)
{
    if (fj_implementation_get_name_ptr != NULL)
        return fj_implementation_get_name_ptr(id);
    return 0;
}

static struct fj_implementation const * (*fj_implementation_get_builtin_ptr)(fj_implementation_id_t id);
struct fj_implementation const * fj_implementation_get_builtin(fj_implementation_id_t id)
{
    if (fj_implementation_get_builtin_ptr != NULL)
        return fj_implementation_get_builtin_ptr(id);
    return 0;
}

static fj_err_t (*fj_implementation_get_default_id_ptr)(fj_implementation_id_t * out_id);
fj_err_t fj_implementation_get_default_id(fj_implementation_id_t * out_id)
{
    if (fj_implementation_get_default_id_ptr != NULL)
        return fj_implementation_get_default_id_ptr(out_id);
    return FJ_ERR_UNSUPPORTED;
}

#include <fejix/interface/opengl.h>


#include <fejix/interface/ram.h>

static fj_err_t (*fj_ram_create_manager_ptr)(struct fj_app * owner_app, struct fj_ram_manager ** out_manager);
fj_err_t fj_ram_create_manager(struct fj_app * owner_app, struct fj_ram_manager ** out_manager)
{
    if (fj_ram_create_manager_ptr != NULL)
        return fj_ram_create_manager_ptr(owner_app, out_manager);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_ram_destroy_manager_ptr)(struct fj_ram_manager * manager);
fj_err_t fj_ram_destroy_manager(struct fj_ram_manager * manager)
{
    if (fj_ram_destroy_manager_ptr != NULL)
        return fj_ram_destroy_manager_ptr(manager);
    return FJ_ERR_UNSUPPORTED;
}

static void (*fj_ram_get_compatible_formats_ptr)(struct fj_ram_manager * manager, fj_ram_pixel_format_t ** out_formats, uint32_t * out_count, struct fj_image_consumer * image_consumer);
void fj_ram_get_compatible_formats(struct fj_ram_manager * manager, fj_ram_pixel_format_t ** out_formats, uint32_t * out_count, struct fj_image_consumer * image_consumer)
{
    if (fj_ram_get_compatible_formats_ptr != NULL)
        fj_ram_get_compatible_formats_ptr(manager, out_formats, out_count, image_consumer);
    /* do nothing by default */;
}

static fj_err_t (*fj_ram_create_images_ptr)(struct fj_ram_manager * manager, struct fj_ram_images ** out_images, fj_ram_pixel_format_t format, struct fj_image_consumer * image_consumer);
fj_err_t fj_ram_create_images(struct fj_ram_manager * manager, struct fj_ram_images ** out_images, fj_ram_pixel_format_t format, struct fj_image_consumer * image_consumer)
{
    if (fj_ram_create_images_ptr != NULL)
        return fj_ram_create_images_ptr(manager, out_images, format, image_consumer);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_ram_destroy_images_ptr)(struct fj_ram_manager * manager, struct fj_ram_images * images);
fj_err_t fj_ram_destroy_images(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    if (fj_ram_destroy_images_ptr != NULL)
        return fj_ram_destroy_images_ptr(manager, images);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_ram_resize_images_ptr)(struct fj_ram_manager * manager, struct fj_ram_images * images);
fj_err_t fj_ram_resize_images(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    if (fj_ram_resize_images_ptr != NULL)
        return fj_ram_resize_images_ptr(manager, images);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_ram_wait_image_available_ptr)(struct fj_ram_manager * manager, struct fj_ram_images * images);
fj_err_t fj_ram_wait_image_available(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    if (fj_ram_wait_image_available_ptr != NULL)
        return fj_ram_wait_image_available_ptr(manager, images);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_ram_get_available_image_info_ptr)(struct fj_ram_manager * manager, struct fj_ram_images * images, struct fj_ram_image_info * out_image_info);
fj_err_t fj_ram_get_available_image_info(struct fj_ram_manager * manager, struct fj_ram_images * images, struct fj_ram_image_info * out_image_info)
{
    if (fj_ram_get_available_image_info_ptr != NULL)
        return fj_ram_get_available_image_info_ptr(manager, images, out_image_info);
    return FJ_ERR_UNSUPPORTED;
}

static fj_err_t (*fj_ram_present_image_ptr)(struct fj_ram_manager * manager, struct fj_ram_images * images);
fj_err_t fj_ram_present_image(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    if (fj_ram_present_image_ptr != NULL)
        return fj_ram_present_image_ptr(manager, images);
    return FJ_ERR_UNSUPPORTED;
}

#include <fejix/interface/scene.h>


#include <fejix/interface/scene_activity_flags.h>


#include <fejix/interface/scene_blending.h>


#include <fejix/interface/scene_identity.h>


#include <fejix/interface/scene_layer.h>


#include <fejix/interface/scene_layout.h>


#include <fejix/interface/scene_layout_input.h>


#include <fejix/interface/scene_layout_size.h>


#include <fejix/interface/scene_role.h>


#include <fejix/interface/scene_sync.h>


#include <fejix/interface/vulkan.h>


char const *function_names[] = {
"fj_app_check_supported",
"fj_app_create",
"fj_app_destroy",
"fj_app_on_idle",
"fj_app_on_finish",
"fj_app_on_notification",
"fj_app_launch",
"fj_app_wakeup_after_timeout",
"fj_app_wakeup_remotely",
"fj_app_set_finished",
"fj_app_activity_flags_get_supported_flags",
"fj_app_activity_flags_set_flags",
"fj_app_manual_sleep_get_supported",
"fj_app_manual_sleep",
"fj_image_consumer_get_desired_size",
"fj_implementation_set_global",
"fj_implementation_get_global",
"fj_implementation_get_name",
"fj_implementation_get_builtin",
"fj_implementation_get_default_id",
"fj_ram_create_manager",
"fj_ram_destroy_manager",
"fj_ram_get_compatible_formats",
"fj_ram_create_images",
"fj_ram_destroy_images",
"fj_ram_resize_images",
"fj_ram_wait_image_available",
"fj_ram_get_available_image_info",
"fj_ram_present_image",
};

void **function_pointers[] = {
(void **) &fj_app_check_supported,
(void **) &fj_app_create,
(void **) &fj_app_destroy,
(void **) &fj_app_on_idle,
(void **) &fj_app_on_finish,
(void **) &fj_app_on_notification,
(void **) &fj_app_launch,
(void **) &fj_app_wakeup_after_timeout,
(void **) &fj_app_wakeup_remotely,
(void **) &fj_app_set_finished,
(void **) &fj_app_activity_flags_get_supported_flags,
(void **) &fj_app_activity_flags_set_flags,
(void **) &fj_app_manual_sleep_get_supported,
(void **) &fj_app_manual_sleep,
(void **) &fj_image_consumer_get_desired_size,
(void **) &fj_implementation_set_global,
(void **) &fj_implementation_get_global,
(void **) &fj_implementation_get_name,
(void **) &fj_implementation_get_builtin,
(void **) &fj_implementation_get_default_id,
(void **) &fj_ram_create_manager,
(void **) &fj_ram_destroy_manager,
(void **) &fj_ram_get_compatible_formats,
(void **) &fj_ram_create_images,
(void **) &fj_ram_destroy_images,
(void **) &fj_ram_resize_images,
(void **) &fj_ram_wait_image_available,
(void **) &fj_ram_get_available_image_info,
(void **) &fj_ram_present_image,
};
