/* Automatically generated by tools/autogen/autogen.py, do not edit! */

#include <src/loader/loader.h>

char const *fj_loader_function_names[] = {
"fj_app_check_supported",
"fj_app_create",
"fj_app_destroy",
"fj_app_on_idle",
"fj_app_on_finish",
"fj_app_on_notification",
"fj_app_launch",
"fj_app_wakeup_after_timeout",
"fj_app_wakeup_remotely",
"fj_app_set_finished",
"fj_app_activity_flags_get_supported_flags",
"fj_app_activity_flags_set_flags",
"fj_app_manual_sleep_get_supported",
"fj_app_manual_sleep",
"fj_image_consumer_get_desired_size",
"fj_implementation_set_global",
"fj_implementation_get_global",
"fj_implementation_get_name",
"fj_implementation_get_builtin",
"fj_implementation_get_default_id",
"fj_ram_create_manager",
"fj_ram_destroy_manager",
"fj_ram_get_compatible_formats",
"fj_ram_create_images",
"fj_ram_destroy_images",
"fj_ram_resize_images",
"fj_ram_wait_image_available",
"fj_ram_get_available_image_info",
"fj_ram_present_image",
};

extern void *_fj_app_check_supported_ptr;
extern void *_fj_app_create_ptr;
extern void *_fj_app_destroy_ptr;
extern void *_fj_app_on_idle_ptr;
extern void *_fj_app_on_finish_ptr;
extern void *_fj_app_on_notification_ptr;
extern void *_fj_app_launch_ptr;
extern void *_fj_app_wakeup_after_timeout_ptr;
extern void *_fj_app_wakeup_remotely_ptr;
extern void *_fj_app_set_finished_ptr;
extern void *_fj_app_activity_flags_get_supported_flags_ptr;
extern void *_fj_app_activity_flags_set_flags_ptr;
extern void *_fj_app_manual_sleep_get_supported_ptr;
extern void *_fj_app_manual_sleep_ptr;
extern void *_fj_image_consumer_get_desired_size_ptr;
extern void *_fj_implementation_set_global_ptr;
extern void *_fj_implementation_get_global_ptr;
extern void *_fj_implementation_get_name_ptr;
extern void *_fj_implementation_get_builtin_ptr;
extern void *_fj_implementation_get_default_id_ptr;
extern void *_fj_ram_create_manager_ptr;
extern void *_fj_ram_destroy_manager_ptr;
extern void *_fj_ram_get_compatible_formats_ptr;
extern void *_fj_ram_create_images_ptr;
extern void *_fj_ram_destroy_images_ptr;
extern void *_fj_ram_resize_images_ptr;
extern void *_fj_ram_wait_image_available_ptr;
extern void *_fj_ram_get_available_image_info_ptr;
extern void *_fj_ram_present_image_ptr;

void **fj_loader_function_pointers[] = {
&_fj_app_check_supported_ptr,
&_fj_app_create_ptr,
&_fj_app_destroy_ptr,
&_fj_app_on_idle_ptr,
&_fj_app_on_finish_ptr,
&_fj_app_on_notification_ptr,
&_fj_app_launch_ptr,
&_fj_app_wakeup_after_timeout_ptr,
&_fj_app_wakeup_remotely_ptr,
&_fj_app_set_finished_ptr,
&_fj_app_activity_flags_get_supported_flags_ptr,
&_fj_app_activity_flags_set_flags_ptr,
&_fj_app_manual_sleep_get_supported_ptr,
&_fj_app_manual_sleep_ptr,
&_fj_image_consumer_get_desired_size_ptr,
&_fj_implementation_set_global_ptr,
&_fj_implementation_get_global_ptr,
&_fj_implementation_get_name_ptr,
&_fj_implementation_get_builtin_ptr,
&_fj_implementation_get_default_id_ptr,
&_fj_ram_create_manager_ptr,
&_fj_ram_destroy_manager_ptr,
&_fj_ram_get_compatible_formats_ptr,
&_fj_ram_create_images_ptr,
&_fj_ram_destroy_images_ptr,
&_fj_ram_resize_images_ptr,
&_fj_ram_wait_image_available_ptr,
&_fj_ram_get_available_image_info_ptr,
&_fj_ram_present_image_ptr,
};

uint32_t fj_loader_function_count = 29;
