/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/opengl.h>

fj_loader_function_t _fj_has_opengl_ptr;
bool fj_has_opengl(void)
{
    if (_fj_has_opengl_ptr != NULL) {
        return ((bool (*)(void)) _fj_has_opengl_ptr)();
    }
    return false;
}

fj_loader_function_t _fj_opengl_has_platform_ptr;
bool fj_opengl_has_platform(fj_opengl_platform_id_t platform_id)
{
    if (_fj_opengl_has_platform_ptr != NULL) {
        return ((bool (*)(fj_opengl_platform_id_t platform_id)) _fj_opengl_has_platform_ptr)(
            platform_id);
    }
    return false;
}

fj_loader_function_t _fj_opengl_create_default_platform_ptr;
fj_err_t fj_opengl_init_default_platform(
    struct fj_app *owner_app,
    struct fj_opengl_platform **out_platform,
    fj_opengl_platform_id_t platform_id)
{
    if (_fj_opengl_create_default_platform_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_app * owner_app,
            struct fj_opengl_platform * *out_platform,
            fj_opengl_platform_id_t platform_id)) _fj_opengl_create_default_platform_ptr)(
            owner_app, out_platform, platform_id);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_destroy_default_platform_ptr;
fj_err_t fj_opengl_deinit_default_platform(
    struct fj_app *owner_app, struct fj_opengl_platform *platform)
{
    if (_fj_opengl_destroy_default_platform_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * owner_app, struct fj_opengl_platform * platform))
                    _fj_opengl_destroy_default_platform_ptr)(owner_app, platform);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_create_manager_ptr;
fj_err_t fj_opengl_create_manager(
    struct fj_app *owner_app,
    struct fj_opengl_manager **out_manager,
    struct fj_opengl_platform const *platform)
{
    if (_fj_opengl_create_manager_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_app * owner_app,
            struct fj_opengl_manager * *out_manager,
            struct fj_opengl_platform const *platform)) _fj_opengl_create_manager_ptr)(
            owner_app, out_manager, platform);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_destroy_manager_ptr;
fj_err_t fj_opengl_destroy_manager(struct fj_opengl_manager *manager)
{
    if (_fj_opengl_destroy_manager_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_opengl_manager * manager))
                    _fj_opengl_destroy_manager_ptr)(manager);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_get_manager_platform_ptr;
void fj_opengl_get_manager_platform(
    struct fj_opengl_manager *manager, struct fj_opengl_platform const **out_platform)
{
    if (_fj_opengl_get_manager_platform_ptr != NULL) {
        ((void (*)(
            struct fj_opengl_manager *manager,
            struct fj_opengl_platform const **out_platform)) _fj_opengl_get_manager_platform_ptr)(
            manager, out_platform);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_opengl_get_manager_extensions_ptr;
char const *fj_opengl_get_manager_extensions(struct fj_opengl_manager *manager)
{
    if (_fj_opengl_get_manager_extensions_ptr != NULL) {
        return ((char const *(*) (struct fj_opengl_manager *manager))
                    _fj_opengl_get_manager_extensions_ptr)(manager);
    }
    return NULL;
}

fj_loader_function_t _fj_opengl_get_manager_feature_flags_ptr;
fj_opengl_feature_flags_t fj_opengl_get_manager_feature_flags(struct fj_opengl_manager *manager)
{
    if (_fj_opengl_get_manager_feature_flags_ptr != NULL) {
        return ((fj_opengl_feature_flags_t(*)(struct fj_opengl_manager * manager))
                    _fj_opengl_get_manager_feature_flags_ptr)(manager);
    }
    return 0;
}

fj_loader_function_t _fj_opengl_create_offscreen_image_binding_ptr;
fj_err_t fj_opengl_create_offscreen_image_binding(
    struct fj_opengl_manager *manager,
    struct fj_image_binding **out_image_binding,
    struct fj_size const *image_size)
{
    if (_fj_opengl_create_offscreen_image_binding_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_image_binding * *out_image_binding,
            struct fj_size const *image_size)) _fj_opengl_create_offscreen_image_binding_ptr)(
            manager, out_image_binding, image_size);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_destroy_offscreen_image_binding_ptr;
fj_err_t fj_opengl_destroy_offscreen_image_binding(
    struct fj_opengl_manager *manager, struct fj_image_binding *image_binding)
{
    if (_fj_opengl_destroy_offscreen_image_binding_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager, struct fj_image_binding * image_binding))
                    _fj_opengl_destroy_offscreen_image_binding_ptr)(manager, image_binding);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_can_bind_ptr;
bool fj_opengl_can_bind(struct fj_opengl_manager *manager, struct fj_image_binding *image_binding)
{
    if (_fj_opengl_can_bind_ptr != NULL) {
        return (
            (bool (*)(struct fj_opengl_manager *manager, struct fj_image_binding *image_binding))
                _fj_opengl_can_bind_ptr)(manager, image_binding);
    }
    return false;
}

fj_loader_function_t _fj_opengl_create_image_format_ptr;
fj_err_t fj_opengl_create_image_format(
    struct fj_opengl_manager *manager,
    struct fj_opengl_image_format **out_image_format,
    struct fj_opengl_attribute_list const *attribute_list,
    struct fj_image_binding *image_binding)
{
    if (_fj_opengl_create_image_format_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_opengl_image_format * *out_image_format,
            struct fj_opengl_attribute_list const *attribute_list,
            struct fj_image_binding *image_binding)) _fj_opengl_create_image_format_ptr)(
            manager, out_image_format, attribute_list, image_binding);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_destroy_image_format_ptr;
fj_err_t fj_opengl_destroy_image_format(
    struct fj_opengl_manager *manager, struct fj_opengl_image_format *image_format)
{
    if (_fj_opengl_destroy_image_format_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager, struct fj_opengl_image_format * image_format))
                    _fj_opengl_destroy_image_format_ptr)(manager, image_format);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_get_image_format_attribute_ptr;
fj_err_t fj_opengl_get_image_format_attribute(
    struct fj_opengl_manager *manager,
    struct fj_opengl_image_format const *image_format,
    fj_opengl_attribute_id_t id,
    fj_opengl_attribute_value_t *out_value)
{
    if (_fj_opengl_get_image_format_attribute_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_opengl_image_format const *image_format,
            fj_opengl_attribute_id_t id,
            fj_opengl_attribute_value_t *out_value)) _fj_opengl_get_image_format_attribute_ptr)(
            manager, image_format, id, out_value);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_create_images_ptr;
fj_err_t fj_opengl_create_images(
    struct fj_opengl_manager *manager,
    struct fj_opengl_images **out_images,
    struct fj_opengl_image_format const *image_format,
    struct fj_image_binding *image_binding)
{
    if (_fj_opengl_create_images_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_opengl_images * *out_images,
            struct fj_opengl_image_format const *image_format,
            struct fj_image_binding *image_binding)) _fj_opengl_create_images_ptr)(
            manager, out_images, image_format, image_binding);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_destroy_images_ptr;
fj_err_t fj_opengl_destroy_images(
    struct fj_opengl_manager *manager, struct fj_opengl_images *images)
{
    if (_fj_opengl_destroy_images_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_opengl_manager * manager, struct fj_opengl_images * images))
                    _fj_opengl_destroy_images_ptr)(manager, images);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_get_images_image_format_ptr;
void fj_opengl_get_images_image_format(
    struct fj_opengl_manager *manager,
    struct fj_opengl_images *images,
    struct fj_opengl_image_format const **out_image_format)
{
    if (_fj_opengl_get_images_image_format_ptr != NULL) {
        ((void (*)(
            struct fj_opengl_manager *manager,
            struct fj_opengl_images *images,
            struct fj_opengl_image_format const **out_image_format))
             _fj_opengl_get_images_image_format_ptr)(manager, images, out_image_format);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_opengl_get_images_platform_object_ptr;
void fj_opengl_get_images_platform_object(
    struct fj_opengl_manager *manager, struct fj_opengl_images *images, void *out_platform_object)
{
    if (_fj_opengl_get_images_platform_object_ptr != NULL) {
        ((void (*)(
            struct fj_opengl_manager *manager,
            struct fj_opengl_images *images,
            void *out_platform_object)) _fj_opengl_get_images_platform_object_ptr)(
            manager, images, out_platform_object);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_opengl_swap_images_ptr;
fj_err_t fj_opengl_swap_images(struct fj_opengl_manager *manager, struct fj_opengl_images *images)
{
    if (_fj_opengl_swap_images_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_opengl_manager * manager, struct fj_opengl_images * images))
                    _fj_opengl_swap_images_ptr)(manager, images);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_create_renderer_ptr;
fj_err_t fj_opengl_create_renderer(
    struct fj_opengl_manager *manager,
    struct fj_opengl_renderer **out_renderer,
    struct fj_opengl_attribute_list attribute_list,
    struct fj_opengl_image_format *image_format,
    struct fj_opengl_renderer *friend_renderer)
{
    if (_fj_opengl_create_renderer_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_opengl_renderer * *out_renderer,
            struct fj_opengl_attribute_list attribute_list,
            struct fj_opengl_image_format * image_format,
            struct fj_opengl_renderer * friend_renderer)) _fj_opengl_create_renderer_ptr)(
            manager, out_renderer, attribute_list, image_format, friend_renderer);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_destroy_renderer_ptr;
fj_err_t fj_opengl_destroy_renderer(
    struct fj_opengl_manager *manager, struct fj_opengl_renderer *renderer)
{
    if (_fj_opengl_destroy_renderer_ptr != NULL) {
        return (
            (fj_err_t(*)(struct fj_opengl_manager * manager, struct fj_opengl_renderer * renderer))
                _fj_opengl_destroy_renderer_ptr)(manager, renderer);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_get_renderer_attribute_ptr;
fj_err_t fj_opengl_get_renderer_attribute(
    struct fj_opengl_manager *manager,
    struct fj_opengl_renderer *renderer,
    fj_opengl_attribute_id_t id,
    fj_opengl_attribute_value_t *out_value)
{
    if (_fj_opengl_get_renderer_attribute_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_opengl_renderer * renderer,
            fj_opengl_attribute_id_t id,
            fj_opengl_attribute_value_t * out_value)) _fj_opengl_get_renderer_attribute_ptr)(
            manager, renderer, id, out_value);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_get_renderer_image_format_ptr;
void fj_opengl_get_renderer_image_format(
    struct fj_opengl_manager *manager,
    struct fj_opengl_renderer *renderer,
    struct fj_opengl_image_format **out_image_format)
{
    if (_fj_opengl_get_renderer_image_format_ptr != NULL) {
        ((void (*)(
            struct fj_opengl_manager *manager,
            struct fj_opengl_renderer *renderer,
            struct fj_opengl_image_format **out_image_format))
             _fj_opengl_get_renderer_image_format_ptr)(manager, renderer, out_image_format);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_opengl_get_renderer_platform_object_ptr;
void fj_opengl_get_renderer_platform_object(
    struct fj_opengl_manager *manager,
    struct fj_opengl_renderer *renderer,
    void *out_platform_object)
{
    if (_fj_opengl_get_renderer_platform_object_ptr != NULL) {
        ((void (*)(
            struct fj_opengl_manager *manager,
            struct fj_opengl_renderer *renderer,
            void *out_platform_object)) _fj_opengl_get_renderer_platform_object_ptr)(
            manager, renderer, out_platform_object);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_opengl_get_renderer_function_getter_ptr;
void fj_opengl_get_renderer_function_getter(
    struct fj_opengl_manager *manager,
    struct fj_opengl_renderer *renderer,
    struct fj_opengl_function_loader const *out_function_loader)
{
    if (_fj_opengl_get_renderer_function_getter_ptr != NULL) {
        ((void (*)(
            struct fj_opengl_manager *manager,
            struct fj_opengl_renderer *renderer,
            struct fj_opengl_function_loader const *out_function_loader))
             _fj_opengl_get_renderer_function_getter_ptr)(manager, renderer, out_function_loader);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_opengl_set_current_in_thread_ptr;
fj_err_t fj_opengl_set_current_in_thread(
    struct fj_opengl_manager *manager,
    struct fj_opengl_renderer *renderer,
    struct fj_opengl_images *read_images,
    struct fj_opengl_images *draw_images)
{
    if (_fj_opengl_set_current_in_thread_ptr != NULL) {
        return ((fj_err_t(*)(
            struct fj_opengl_manager * manager,
            struct fj_opengl_renderer * renderer,
            struct fj_opengl_images * read_images,
            struct fj_opengl_images * draw_images)) _fj_opengl_set_current_in_thread_ptr)(
            manager, renderer, read_images, draw_images);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_unset_current_in_thread_ptr;
fj_err_t fj_opengl_unset_current_in_thread(struct fj_opengl_manager *manager)
{
    if (_fj_opengl_unset_current_in_thread_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_opengl_manager * manager))
                    _fj_opengl_unset_current_in_thread_ptr)(manager);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_opengl_set_dummy_current_in_thread_ptr;
fj_err_t fj_opengl_set_dummy_current_in_thread(struct fj_opengl_manager *manager)
{
    if (_fj_opengl_set_dummy_current_in_thread_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_opengl_manager * manager))
                    _fj_opengl_set_dummy_current_in_thread_ptr)(manager);
    }
    return FJ_ERR_UNIMPLEMENTED;
}
