/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/view.h>

fj_loader_function_t _fj_has_view_ptr;
bool fj_has_view(void)
{
    if (_fj_has_view_ptr != NULL) {
        return ((bool(*)(void))_fj_has_view_ptr)();
    }
    return false;
}

fj_loader_function_t _fj_view_create_manager_ptr;
fj_err_t fj_view_create_manager(struct fj_app * owner_app, struct fj_view_manager ** out_manager)
{
    if (_fj_view_create_manager_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * owner_app, struct fj_view_manager ** out_manager))_fj_view_create_manager_ptr)(owner_app, out_manager);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_view_destroy_manager_ptr;
fj_err_t fj_view_destroy_manager(struct fj_view_manager * manager)
{
    if (_fj_view_destroy_manager_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_view_manager * manager))_fj_view_destroy_manager_ptr)(manager);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_view_create_ptr;
fj_err_t fj_view_create(struct fj_view_manager * manager, struct fj_view ** out_view, void * userdata)
{
    if (_fj_view_create_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_view_manager * manager, struct fj_view ** out_view, void * userdata))_fj_view_create_ptr)(manager, out_view, userdata);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_view_destroy_ptr;
fj_err_t fj_view_destroy(struct fj_view_manager * manager, struct fj_view * view)
{
    if (_fj_view_destroy_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_view_manager * manager, struct fj_view * view))_fj_view_destroy_ptr)(manager, view);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

fj_loader_function_t _fj_view_on_bind_images_ptr;
void fj_view_on_bind_images(struct fj_view_manager * manager, fj_view_on_bind_images_fn_t callback)
{
    if (_fj_view_on_bind_images_ptr != NULL) {
        ((void(*)(struct fj_view_manager * manager, fj_view_on_bind_images_fn_t callback))_fj_view_on_bind_images_ptr)(manager, callback);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_view_on_dismiss_ptr;
void fj_view_on_dismiss(struct fj_view_manager * manager, fj_view_on_dismiss_fn_t callback)
{
    if (_fj_view_on_dismiss_ptr != NULL) {
        ((void(*)(struct fj_view_manager * manager, fj_view_on_dismiss_fn_t callback))_fj_view_on_dismiss_ptr)(manager, callback);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_view_on_update_geometry_ptr;
void fj_view_on_update_geometry(struct fj_view_manager * manager, fj_view_on_update_geometry_fn_t callback)
{
    if (_fj_view_on_update_geometry_ptr != NULL) {
        ((void(*)(struct fj_view_manager * manager, fj_view_on_update_geometry_fn_t callback))_fj_view_on_update_geometry_ptr)(manager, callback);
    }
    /* do nothing by default */;
}

fj_loader_function_t _fj_view_update_batch_ptr;
fj_err_t fj_view_update_batch(struct fj_view_manager * manager, struct fj_view *const * views, uint32_t view_count)
{
    if (_fj_view_update_batch_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_view_manager * manager, struct fj_view *const * views, uint32_t view_count))_fj_view_update_batch_ptr)(manager, views, view_count);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

