/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader/loader.h>

#include <fejix/interface/vulkan.h>

fj_loader_function_t _fj_has_vulkan_ptr;
bool fj_has_vulkan(void)
{
    if (_fj_has_vulkan_ptr != NULL) {
        return ((bool(*)(void))_fj_has_vulkan_ptr)();
    }
    return false;
}

fj_loader_function_t _fj_vulkan_create_surface_ptr;
fj_err_t fj_vulkan_create_surface(struct fj_app * app, void * out_surface, struct fj_image_binding * image_binding, struct fj_vulkan_global_info const * global_info)
{
    if (_fj_vulkan_create_surface_ptr != NULL) {
        return ((fj_err_t(*)(struct fj_app * app, void * out_surface, struct fj_image_binding * image_binding, struct fj_vulkan_global_info const * global_info))_fj_vulkan_create_surface_ptr)(app, out_surface, image_binding, global_info);
    }
    return FJ_ERR_UNIMPLEMENTED;
}

