/* Automatically generated by tools/autogen.py, do not edit! */

#include <src/loader.h>

#include <fejix/interface/image.h>

fj_loader_function_t _fj_image_create_event_get_desired_size_ptr;
void fj_image_create_event_get_desired_size(struct fj_image_create_event * crete_event, struct fj_size * out_size)
{
    if (_fj_image_create_event_get_desired_size_ptr != NULL) {
        ((void(*)(struct fj_image_create_event * crete_event, struct fj_size * out_size))_fj_image_create_event_get_desired_size_ptr)(crete_event, out_size);
    }
    /* do nothing by default */;
}

