/* Automatically generated by tools/autogen.py, do not edit! */
#include <src/loader.h>
char const *fj_loader_function_names[] = {
    "fj_app_check_supported",
    "fj_app_create",
    "fj_app_destroy",
    "fj_app_on_idle",
    "fj_app_on_finish",
    "fj_app_on_notification",
    "fj_app_launch",
    "fj_app_wakeup_after_timeout",
    "fj_app_wakeup_remotely",
    "fj_app_set_finished",
    "fj_app_activity_flags_get_supported_flags",
    "fj_app_activity_flags_set_flags",
    "fj_app_manual_sleep_get_supported",
    "fj_app_manual_sleep",
    "fj_image_create_event_get_desired_size",
    "fj_implementation_get_id",
    "fj_implementation_get_name",
    "fj_implementation_get_version",
    "fj_ram_create_manager",
    "fj_ram_destroy_manager",
    "fj_ram_get_compatible_formats",
    "fj_ram_create_images",
    "fj_ram_destroy_images",
    "fj_ram_resize_images",
    "fj_ram_wait_image_available",
    "fj_ram_get_available_image_info",
    "fj_ram_present_image",
};
extern fj_loader_function_t _fj_app_check_supported_ptr;
extern fj_loader_function_t _fj_app_create_ptr;
extern fj_loader_function_t _fj_app_destroy_ptr;
extern fj_loader_function_t _fj_app_on_idle_ptr;
extern fj_loader_function_t _fj_app_on_finish_ptr;
extern fj_loader_function_t _fj_app_on_notification_ptr;
extern fj_loader_function_t _fj_app_launch_ptr;
extern fj_loader_function_t _fj_app_wakeup_after_timeout_ptr;
extern fj_loader_function_t _fj_app_wakeup_remotely_ptr;
extern fj_loader_function_t _fj_app_set_finished_ptr;
extern fj_loader_function_t _fj_app_activity_flags_get_supported_flags_ptr;
extern fj_loader_function_t _fj_app_activity_flags_set_flags_ptr;
extern fj_loader_function_t _fj_app_manual_sleep_get_supported_ptr;
extern fj_loader_function_t _fj_app_manual_sleep_ptr;
extern fj_loader_function_t _fj_image_create_event_get_desired_size_ptr;
extern fj_loader_function_t _fj_implementation_get_id_ptr;
extern fj_loader_function_t _fj_implementation_get_name_ptr;
extern fj_loader_function_t _fj_implementation_get_version_ptr;
extern fj_loader_function_t _fj_ram_create_manager_ptr;
extern fj_loader_function_t _fj_ram_destroy_manager_ptr;
extern fj_loader_function_t _fj_ram_get_compatible_formats_ptr;
extern fj_loader_function_t _fj_ram_create_images_ptr;
extern fj_loader_function_t _fj_ram_destroy_images_ptr;
extern fj_loader_function_t _fj_ram_resize_images_ptr;
extern fj_loader_function_t _fj_ram_wait_image_available_ptr;
extern fj_loader_function_t _fj_ram_get_available_image_info_ptr;
extern fj_loader_function_t _fj_ram_present_image_ptr;
fj_loader_function_t *fj_loader_function_pointers[] = {
    (fj_loader_function_t*)&_fj_app_check_supported_ptr,
    (fj_loader_function_t*)&_fj_app_create_ptr,
    (fj_loader_function_t*)&_fj_app_destroy_ptr,
    (fj_loader_function_t*)&_fj_app_on_idle_ptr,
    (fj_loader_function_t*)&_fj_app_on_finish_ptr,
    (fj_loader_function_t*)&_fj_app_on_notification_ptr,
    (fj_loader_function_t*)&_fj_app_launch_ptr,
    (fj_loader_function_t*)&_fj_app_wakeup_after_timeout_ptr,
    (fj_loader_function_t*)&_fj_app_wakeup_remotely_ptr,
    (fj_loader_function_t*)&_fj_app_set_finished_ptr,
    (fj_loader_function_t*)&_fj_app_activity_flags_get_supported_flags_ptr,
    (fj_loader_function_t*)&_fj_app_activity_flags_set_flags_ptr,
    (fj_loader_function_t*)&_fj_app_manual_sleep_get_supported_ptr,
    (fj_loader_function_t*)&_fj_app_manual_sleep_ptr,
    (fj_loader_function_t*)&_fj_image_create_event_get_desired_size_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_id_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_name_ptr,
    (fj_loader_function_t*)&_fj_implementation_get_version_ptr,
    (fj_loader_function_t*)&_fj_ram_create_manager_ptr,
    (fj_loader_function_t*)&_fj_ram_destroy_manager_ptr,
    (fj_loader_function_t*)&_fj_ram_get_compatible_formats_ptr,
    (fj_loader_function_t*)&_fj_ram_create_images_ptr,
    (fj_loader_function_t*)&_fj_ram_destroy_images_ptr,
    (fj_loader_function_t*)&_fj_ram_resize_images_ptr,
    (fj_loader_function_t*)&_fj_ram_wait_image_available_ptr,
    (fj_loader_function_t*)&_fj_ram_get_available_image_info_ptr,
    (fj_loader_function_t*)&_fj_ram_present_image_ptr,
};
uint32_t fj_loader_function_count = 27;
