# List of planned options:
# PLATFORM_X11
# PLATFORM_WAYLAND
# PLATFORM_WINAPI
# PLATFORM_COCOA
# PLATFORM_UIKIT
# PLATFORM_ANDROID
# FEATURE_UNIXPOLLER
# FEATURE_SHELL
# FEATURE_WM
# FEATURE_INPUT
# FEATURE_INPUTMETHOD
# FEATURE_CLIPBOARD
# FEATURE_GRAPHICS
# FEATURE_RASTER
# FEATURE_OPENGL
# FEATURE_VULKAN
# FEATURE_DIRECTX
# FEATURE_METAL
# FEATURE_SYSREDRAW
# FEATURE_SYSINFO
# FEATURE_SYSTRAY


option(FEJIX_PLATFORM_X11 OFF)
option(FEJIX_PLATFORM_WINAPI OFF)
option(FEJIX_FEATURE_UNIXPOLLER OFF)
option(FEJIX_FEATURE_SHELL OFF)


if(FEJIX_PLATFORM_X11)
    set(FEJIX_FEATURE_UNIXPOLLER ON)
endif()


if(FEJIX_PLATFORM_WINAPI)
    add_compile_definitions("FJ_PLATFORM_WINAPI")
endif()

if(FEJIX_PLATFORM_X11)
    add_compile_definitions("FJ_PLATFORM_X11")
endif()

if(FEJIX_FEATURE_SHELL)
    add_compile_definitions("FJ_FEATURE_SHELL")
endif()

if(FEJIX_FEATURE_UNIXPOLLER)
    add_compile_definitions("FJ_FEATURE_UNIXPOLLER")
endif()
