/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/app.h>

bool fj_has_app(void)
{

    return false;
}

fj_err_t fj_app_create(struct fj_app ** out_app, void * app_userdata)
{
    (void) out_app; (void) app_userdata;
    return FJ_ERR_UNIMPLEMENTED;
}

fj_err_t fj_app_destroy(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNIMPLEMENTED;
}

void fj_app_on_continue(struct fj_app * app, fj_app_on_continue_fn_t callback)
{
    (void) app; (void) callback;
    /* do nothing by default */;
}

void f_app_on_suspend(struct fj_app * app, fj_app_on_suspend_fn_t callback)
{
    (void) app; (void) callback;
    /* do nothing by default */;
}

void fj_app_on_finish(struct fj_app * app, fj_app_on_finish_fn_t callback)
{
    (void) app; (void) callback;
    /* do nothing by default */;
}

fj_err_t fj_app_launch(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNIMPLEMENTED;
}

fj_err_t fj_app_request_continue(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNIMPLEMENTED;
}

fj_err_t fj_app_request_finish(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNIMPLEMENTED;
}

