/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/app_manual_sleep.h>

bool fj_app_manual_sleep_get_interface_version(void)
{

    return 0;
}

fj_err_t fj_app_manual_sleep(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNSUPPORTED;
}

