/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/app_manual_sleep.h>

bool fj_has_app_manual_sleep(void)
{

    return false;
}

fj_err_t fj_app_manual_sleep(struct fj_app * app)
{
    (void) app;
    return FJ_ERR_UNIMPLEMENTED;
}

