/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/implementation.h>

char const * fj_implementation_get_name(void)
{

    return NULL;
}

fj_version_t fj_implementation_get_version(void)
{

    return 0;
}

