/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/ram.h>

fj_version_t fj_ram_get_interface_version(void)
{

    return 0;
}

fj_err_t fj_ram_create_manager(struct fj_app * owner_app, struct fj_ram_manager ** out_manager)
{
    (void) owner_app; (void) out_manager;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_ram_destroy_manager(struct fj_ram_manager * manager)
{
    (void) manager;
    return FJ_ERR_UNSUPPORTED;
}

void fj_ram_get_supported_formats(struct fj_ram_manager * manager, fj_ram_pixel_format_t ** out_formats, uint32_t * out_count, struct fj_image_bind_context * image_bind_context)
{
    (void) manager; (void) out_formats; (void) out_count; (void) image_bind_context;
    /* do nothing by default */;
}

fj_err_t fj_ram_create_images(struct fj_ram_manager * manager, struct fj_ram_images ** out_images, fj_ram_pixel_format_t format, struct fj_image_bind_context * image_bind_context)
{
    (void) manager; (void) out_images; (void) format; (void) image_bind_context;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_ram_destroy_images(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    (void) manager; (void) images;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_ram_resize_images(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    (void) manager; (void) images;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_ram_wait_image_available(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    (void) manager; (void) images;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_ram_get_available_image_info(struct fj_ram_manager * manager, struct fj_ram_images * images, struct fj_ram_image_info * out_image_info)
{
    (void) manager; (void) images; (void) out_image_info;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_ram_present_image(struct fj_ram_manager * manager, struct fj_ram_images * images)
{
    (void) manager; (void) images;
    return FJ_ERR_UNSUPPORTED;
}

