/* Automatically generated by tools/autogen.py, do not edit! */

#include <fejix/interface/view.h>

fj_version_t fj_view_get_interface_version(void)
{

    return 0;
}

fj_err_t fj_view_create_manager(struct fj_app * owner_app, struct fj_view_manager ** out_manager)
{
    (void) owner_app; (void) out_manager;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_view_destroy_manager(struct fj_view_manager * manager)
{
    (void) manager;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_view_create(struct fj_view_manager * manager, struct fj_view ** out_view, void * userdata)
{
    (void) manager; (void) out_view; (void) userdata;
    return FJ_ERR_UNSUPPORTED;
}

fj_err_t fj_view_destroy(struct fj_view_manager * manager, struct fj_view * view)
{
    (void) manager; (void) view;
    return FJ_ERR_UNSUPPORTED;
}

void fj_view_on_bind_images(struct fj_view_manager * manager, fj_view_on_bind_images_fn_t callback)
{
    (void) manager; (void) callback;
    /* do nothing by default */;
}

void fj_view_on_dismiss(struct fj_view_manager * manager, fj_view_on_dismiss_fn_t callback)
{
    (void) manager; (void) callback;
    /* do nothing by default */;
}

void fj_view_on_update_geometry(struct fj_view_manager * manager, fj_view_on_update_geometry_fn_t callback)
{
    (void) manager; (void) callback;
    /* do nothing by default */;
}

fj_err_t fj_view_update_batch(struct fj_view_manager * manager, struct fj_view *const * views, uint32_t view_count)
{
    (void) manager; (void) views; (void) view_count;
    return FJ_ERR_UNSUPPORTED;
}

